### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by kylichist** [crinny/b0mb3r-beta#3]
После установки по Android инструкции при всех запусках команды "b0mb3r" вылетает такая ошибка

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/b0mb3r", line 11, in <module>
    load_entry_point('b0mb3r==2.0.0', 'console_scripts', 'b0mb3r')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/b0mb3r/__main__.py", line 29, in main
    time.sleep(1)
NameError: name 'time' is not defined

**Comment by themakci7m87** [comment]
++
Тоже самое

**Comment by crinny** [comment]
Исправлено. Переустановите b0mb3r
